### ISSUE TITLE
Kick speed for Druid should consider weapon type

### ISSUE THREAD

**Issue by tcbbd** [Warren1001/IAS_Calculator#10]
From AnimData.D2, I found that the AnimationSpeed=224 for Druid's Kick action, when he is using 1HS/2HS weapons.

**Comment by Warren1001** [comment]
Interesting. Once all the 2.4 changes are finalized and well tested, I'll get around to the kick animations and verify that they're all correct. Thanks for the headsup, probably saved me some future trouble looking through stuff til I found that.

**Comment by Warren1001** [comment]
fixed in the latest update. assuming that difference is the only unique case for kicks, they should all be correct (tested)
