### ISSUE TITLE
Maul % ias not in the calculator

### ISSUE THREAD

**Issue by DM-ICE** [Warren1001/IAS_Calculator#2]
Please add Maul skill and lvl 1-60 slider for it so we can calculate our attack speed.

**Comment by Warren1001** [comment]
hi, its on my todo. fury currently has my full focus but i may add it
before finishing fury if fury keeps giving me troubles. i'll probably be a
few days before i do it :)

**Comment by Warren1001** [comment]
updated the calculator, has maul stuff now
