### ISSUE TITLE
Ogre Maul (10) needs 125 IAS for 5 frames, but Colossus Blade (5) needs only 75 IAS for 4 frames

### ISSUE THREAD

**Issue by ceving** [Warren1001/IAS_Calculator#20]
This is the IAS table for Ogre Maul:

https://warren1001.github.io/IAS_Calculator/?data=2-0-Ogre_Maul-0-0-None-0-Whirlwind-1-0-0-0-0-0-0-0-0-0-0

IAS | FPA
--- | ---
0 | 9
13 | 8
29 | 7
58 | 6
125 | 5

And this is for a Colossus Blade:

https://warren1001.github.io/IAS_Calculator/?data=2-0-Colossus_Blade-0-0-None-0-Whirlwind-1-0-0-0-0-0-0-0-0-0-0

IAS | FPA
--- | ---
0 | 7
7 | 6
27 | 5
75 | 4

It is hard to believe, that this huge difference is correct.

**Comment by Warren1001** [comment]
its correct. whirlwind uses one handed breakpoints for two handed swords no
matter what
