### ISSUE TITLE
Maul attack speed

### ISSUE THREAD

**Issue by DM-ICE** [Warren1001/IAS_Calculator#3]
I'm looking at the frames with Thresher for WW and WB. Shouldn't they reach the same frames with the same skill ias?
For me it looks like a 22 Maul hits the same as a lvl 16 WW skill. Looking at Arreat Summit level 16 WW is 66% sias - the same as a level 38 Maul in game tooltip for me. 
I have 55ias on to hit 7 frame BP and it feels like I am hitting a BP with 38 maul and not 37. 
Looking at the current state of the calculator it shows 6 fframes for both 37 and 38. But I'm fairly confident I'm only hitting 7 frames and only at lvl 38 Maul, not 37. 
Perhaps the current calculation takes 3% for every level Maul and not every even skill level or something?
Because every change to maul slvl I change alters the numbers for ias needed.

**Comment by Warren1001** [comment]
i know what my mistake was. i forgot to account for the fact that slvl =/=
amount of charges. right now it gives 3 sias per level instead of
floor(slvl/2)+3 (iirc). ill fix that shortly

**Comment by Warren1001** [comment]
should be fixed now
