### ISSUE TITLE
Amazon IMPALE with Ceremonial Javalins WRONG Breakpoints ?

### ISSUE THREAD

**Issue by einfachIGGI** [Warren1001/IAS_Calculator#30]
Hello guys, i just tried to calculate how much IAS i need on my switch 3sox shield (atm with ttans in use!) and checked different calculators i ussualy used, and even the d2planner of GG said the same IAS, (i need total of 125ias+ to reach 15Fpa)

on warrens calculator it says this

IAS | FPA
-- | --
0 | 20
2 | 19
8 | 18
16 | 17
27 | 16
42 | 15
60 | 14
92 | 13
142 | 12

----------------------------------------------------------

on all others calculators i tried and on d2planner itself it says this:

https://i.imgur.com/6syIdyA.png

so im really confused, someone check anything? (i should try it out but got no items for atm) to test 1x15ias and 3x15ias if i see / feel / hear a difference on attackspeed 

regards

**Comment by Warren1001** [comment]
that's not d2planner, and that calculator hasnt been updated for d2r. impale underwent attack speed changes, so my calculator is correct. d2planner is pretty behind on some skills changes.

**Comment by einfachIGGI** [comment]
> that's not d2planner, and that calculator hasnt been updated for d2r. impale underwent attack speed changes, so my calculator is correct. d2planner is pretty behind on some skills changes.

thx man! i just was wondering i try around 5 ias calculators on web and all was the same with the 125ias / 168Ias thingy
i use ur calc now and thx for reply <3
